### info 확인 - application.yml 에서 입력, vmoption 으로 입력 가능 / git, build 안보이는경우라면 , mvn clean install
GET http://localhost:8080/actuator/info



### env - 전체 환경변수가 보임
GET http://localhost:8080/actuator/env
