### ACTUATOR
GET http://localhost:8080/actuator

### GET
GET http://localhost:8080/actuator/myLibraryInfo?includeVersion=true
Content-Type: application/json

### GET
GET http://localhost:8080/actuator/myLibraryInfo?includeVersion=false
Content-Type: application/json

### GET
GET http://localhost:8080/actuator/myLibraryInfo?includeVersion=false&name=jackson
Content-Type: application/json


### POST
POST http://localhost:8080/actuator/myLibraryInfo
Content-Type: application/json

{
  "name": "test1",
  "enableSomething": false
}

### PathVariable Test
GET http://localhost:8080/actuator/myLibraryInfo/111/222
Content-Type: application/json


### CUSTOM - HEALTH
GET http://localhost:8080/actuator/health


### INFO
GET http://localhost:8080/actuator/info

### INFO
GET http://localhost:8080/actuator/env

### INFO
GET http://localhost:8080/actuator/caches